//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Icatt.DotNetNuke.Modules.Geeltjes.DataAccess
{
    public partial class Icatt_Geeltjes_UserGeeltje
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int GeeltjeId
        {
            get { return _geeltjeId; }
            set
            {
                if (_geeltjeId != value)
                {
                    if (Icatt_Geeltjes_Geeltje != null && Icatt_Geeltjes_Geeltje.Id != value)
                    {
                        Icatt_Geeltjes_Geeltje = null;
                    }
                    _geeltjeId = value;
                }
            }
        }
        private int _geeltjeId;
    
        public virtual int UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (Users != null && Users.UserID != value)
                    {
                        Users = null;
                    }
                    _userId = value;
                }
            }
        }
        private int _userId;
    
        public virtual Nullable<int> ThumbUp
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ThumbDown
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Icatt_Geeltjes_Geeltje Icatt_Geeltjes_Geeltje
        {
            get { return _icatt_Geeltjes_Geeltje; }
            set
            {
                if (!ReferenceEquals(_icatt_Geeltjes_Geeltje, value))
                {
                    var previousValue = _icatt_Geeltjes_Geeltje;
                    _icatt_Geeltjes_Geeltje = value;
                    FixupIcatt_Geeltjes_Geeltje(previousValue);
                }
            }
        }
        private Icatt_Geeltjes_Geeltje _icatt_Geeltjes_Geeltje;
    
        public virtual Users Users
        {
            get { return _users; }
            set
            {
                if (!ReferenceEquals(_users, value))
                {
                    var previousValue = _users;
                    _users = value;
                    FixupUsers(previousValue);
                }
            }
        }
        private Users _users;

        #endregion

        #region Association Fixup
    
        private void FixupIcatt_Geeltjes_Geeltje(Icatt_Geeltjes_Geeltje previousValue)
        {
            if (previousValue != null && previousValue.Icatt_Geeltjes_UserGeeltje.Contains(this))
            {
                previousValue.Icatt_Geeltjes_UserGeeltje.Remove(this);
            }
    
            if (Icatt_Geeltjes_Geeltje != null)
            {
                if (!Icatt_Geeltjes_Geeltje.Icatt_Geeltjes_UserGeeltje.Contains(this))
                {
                    Icatt_Geeltjes_Geeltje.Icatt_Geeltjes_UserGeeltje.Add(this);
                }
                if (GeeltjeId != Icatt_Geeltjes_Geeltje.Id)
                {
                    GeeltjeId = Icatt_Geeltjes_Geeltje.Id;
                }
            }
        }
    
        private void FixupUsers(Users previousValue)
        {
            if (previousValue != null && previousValue.Icatt_Geeltjes_UserGeeltje.Contains(this))
            {
                previousValue.Icatt_Geeltjes_UserGeeltje.Remove(this);
            }
    
            if (Users != null)
            {
                if (!Users.Icatt_Geeltjes_UserGeeltje.Contains(this))
                {
                    Users.Icatt_Geeltjes_UserGeeltje.Add(this);
                }
                if (UserId != Users.UserID)
                {
                    UserId = Users.UserID;
                }
            }
        }

        #endregion

    }
}
