//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Icatt.DotNetNuke.Modules.Geeltjes.DataAccess
{
    public partial class Modules
    {
        #region Primitive Properties
    
        public virtual int ModuleID
        {
            get;
            set;
        }
    
        public virtual int ModuleDefID
        {
            get;
            set;
        }
    
        public virtual bool AllTabs
        {
            get;
            set;
        }
    
        public virtual bool IsDeleted
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> InheritViewPermissions
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> StartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PortalID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CreatedByUserID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedOnDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LastModifiedByUserID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastModifiedOnDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ContentItemID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastContentModifiedOnDate
        {
            get;
            set;
        }
    
        public virtual bool IsShareable
        {
            get;
            set;
        }
    
        public virtual bool IsShareableViewOnly
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Icatt_Geeltjes_Geeltje> Icatt_Geeltjes_Geeltje
        {
            get
            {
                if (_icatt_Geeltjes_Geeltje == null)
                {
                    var newCollection = new FixupCollection<Icatt_Geeltjes_Geeltje>();
                    newCollection.CollectionChanged += FixupIcatt_Geeltjes_Geeltje;
                    _icatt_Geeltjes_Geeltje = newCollection;
                }
                return _icatt_Geeltjes_Geeltje;
            }
            set
            {
                if (!ReferenceEquals(_icatt_Geeltjes_Geeltje, value))
                {
                    var previousValue = _icatt_Geeltjes_Geeltje as FixupCollection<Icatt_Geeltjes_Geeltje>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupIcatt_Geeltjes_Geeltje;
                    }
                    _icatt_Geeltjes_Geeltje = value;
                    var newValue = value as FixupCollection<Icatt_Geeltjes_Geeltje>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupIcatt_Geeltjes_Geeltje;
                    }
                }
            }
        }
        private ICollection<Icatt_Geeltjes_Geeltje> _icatt_Geeltjes_Geeltje;

        #endregion

        #region Association Fixup
    
        private void FixupIcatt_Geeltjes_Geeltje(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Icatt_Geeltjes_Geeltje item in e.NewItems)
                {
                    item.Modules = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Icatt_Geeltjes_Geeltje item in e.OldItems)
                {
                    if (ReferenceEquals(item.Modules, this))
                    {
                        item.Modules = null;
                    }
                }
            }
        }

        #endregion

    }
}
